### ISSUE TITLE
Report plz

### ISSUE THREAD

**Issue by RAKSHITHA72** [aniket9960/android-currency_Convertor#1]

**Comment by aniket9960** [comment]
The currency convertor application developed by us is developed by using java language as it is one of the popular languages for android development and latter being the official programming language for making apps in android studio. Different countries use different currency, and there is daily variation in these currencies relative to one another. Those who transfer money from one country to another (one currency to another) must be updated with the latest currency exchange rates in the market. 

Currency converter mini project is built keeping this thing in mind. It is simply a calculator-like app. In this application, there is regular update about currency of every country by which it fetches present currency market value and conversion rate.
Such application can be used by any user, but it is mainly useful for business, shares, and finance related areas where money transfer and currency exchange take place on a daily basis.
In this currency converter app, users are provided with an option to select the type of conversion, i.e., from “this” currency to “that” currency. This simple feature allows users to enter amount to be converted (say currency in Dollars), and display the converted amount (say currency in Euro).
